version: "3"

vars:
  NAME: cubey
  # PACKAGE: engine

tasks:
  clean:
    cmds:
      - rmdir .build/
  debug:
    aliases: [default]
    sources:
      - ./**/*.odin
    generates:
      - ./{{.NAME}}.exe
      # - ./{{.NAME}}
    cmds:
      # - odin build . -out:"{{.NAME}}"
      - mkdir -p .build
      - odin build . -debug -out:".build/{{.NAME}}.exe"
      # - nix-shell ../../shell.nix --run 'autoPatchelf {{.NAME}}.elf'
      # - nix-shell ../../shell.nix --run 'patchelf {{.NAME}}.elf --add-needed libvulkan.so.1'
